name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # dump github context
          jq -C . <<< '${{ toJSON(github) }}'

      - name: Test 1
        uses: ./
        with:
          key: test1
          comment: key=test1 v1 - This is a dummy comment. (${{ github.run_id }})

      - name: Test 1
        uses: ./
        with:
          key: test1
          comment: key=test1 v2 - This is a dummy comment. (${{ github.run_id }})

      - name: Test 1 delete
        uses: ./
        with:
          match: all
          key: test1
          operation: delete

      - name: Test 1
        uses: ./
        with:
          key: test1
          comment: key=test1 v1 - This is a dummy comment. (${{ github.run_id }})

      - name: Test 1
        uses: ./
        with:
          key: test1
          comment: key=test1 v2 - This is a dummy comment. (${{ github.run_id }})

      - run: sleep 5

      - name: Test 2
        uses: ./
        with:
          key: test2
          comment: Testx2 upsert - ${{ github.run_id }}

      - name: Test 1 get
        id: t1get
        uses: ./
        with:
          key: test1
          operation: get

      - name: Test 1 upsert
        uses: ./
        with:
          key: test1
          match: first
          ids: ${{ steps.t1get.outputs.ids }}
          comment: key=test1 v1 - This is updated dummy comment. (${{ github.run_id }})

      - run: sleep 5

      - name: Test 1 upsert fresh
        uses: ./
        with:
          key: test1
          comment: key=test1 - This is final dummy comment. (${{ github.run_id }})
